/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snooping;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author engma
 */
public class SnoopingTest extends javax.swing.JFrame {

    /**
     * Creates new form SnoopingTest
     */
    public SnoopingTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Block0 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        Block1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        Block2 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        Block3 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Block4 = new javax.swing.JList();
        AnnouncePanel = new javax.swing.JPanel();
        Announce = new javax.swing.JLabel();
        ShareButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Line0P1 = new javax.swing.JList();
        jScrollPane8 = new javax.swing.JScrollPane();
        Block6 = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        Line0StatePaneP1 = new javax.swing.JPanel();
        Line0StateLabelP1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        AddressP1BlockNo = new javax.swing.JSpinner();
        AddressP1VariableNo = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        ReadBP1 = new javax.swing.JButton();
        EditTextP1 = new javax.swing.JTextField();
        WriteBP1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        ValueLabelP1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        Line0P2 = new javax.swing.JList();
        jScrollPane12 = new javax.swing.JScrollPane();
        Block10 = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        Line0StatePaneP2 = new javax.swing.JPanel();
        Line0StateLabelP2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        AddressP2BlockNo1 = new javax.swing.JSpinner();
        AddressP2VariableNo1 = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        ReadBP2 = new javax.swing.JButton();
        EditTextP2 = new javax.swing.JTextField();
        WriteBP2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        ValueLabelP2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        Line0P3 = new javax.swing.JList();
        jScrollPane15 = new javax.swing.JScrollPane();
        Block13 = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        AddressP3BlockNo2 = new javax.swing.JSpinner();
        AddressP3VariableNo2 = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        ReadBP3 = new javax.swing.JButton();
        EditTextP3 = new javax.swing.JTextField();
        WriteBP3 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        ValueLabelP3 = new javax.swing.JLabel();
        Line0StateLabelP3 = new javax.swing.JLabel();
        Line0StatePaneP3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
		listModel0P1 = new DefaultListModel<>(); 
		listModel0P2 = new DefaultListModel<>(); 
		listModel0P3 = new DefaultListModel<>(); 
		DefaultListModel ll = new DefaultListModel<>();
		for(int h = 0 ; h <  8; h++)
		{
			ll.addElement(0);
			listModel0P1.addElement(0);
			listModel0P2.addElement(0);
			listModel0P3.addElement(0);
			
		}
			listModelBlocks = new ArrayList<>(); 
		listModelBlocks.add(ll);
		listModelBlocks.add(ll);
		listModelBlocks.add(ll);
		listModelBlocks.add(ll);
		
        Block0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Block0.setModel(listModelBlocks.get(0));
        Block0.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Block0);

        Block1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Block1.setModel(listModelBlocks.get(1));
        Block1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(Block1);

        Block2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Block2.setModel(listModelBlocks.get(2));
        Block2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(Block2);

        Block3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Block3.setModel(listModelBlocks.get(3));
        Block3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(Block3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Block0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Block1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Block2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Block3");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Memory");

        Block4.setBackground(new java.awt.Color(204, 204, 204));
        Block4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Block4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Var 0", "Var 1", "Var 2", "Var 3", "Var 4", "Var 5", "Var 6", "Var 7" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(Block4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(190, 190, 190))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        AnnouncePanel.setBackground(new java.awt.Color(102, 102, 102));

        Announce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Announce.setForeground(new java.awt.Color(255, 255, 255));

        ShareButton.setText("Share");
        ShareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShareButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AnnouncePanelLayout = new javax.swing.GroupLayout(AnnouncePanel);
        AnnouncePanel.setLayout(AnnouncePanelLayout);
        AnnouncePanelLayout.setHorizontalGroup(
            AnnouncePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnnouncePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Announce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnnouncePanelLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(ShareButton)
                .addGap(103, 103, 103))
        );
        AnnouncePanelLayout.setVerticalGroup(
            AnnouncePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnnouncePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Announce, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShareButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Bus");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        Line0P1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Line0P1.setModel(listModel0P1);
        Line0P1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane7.setViewportView(Line0P1);

        Block6.setBackground(new java.awt.Color(204, 204, 204));
        Block6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Block6.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Var 0", "Var 1", "Var 2", "Var 3", "Var 4", "Var 5", "Var 6", "Var 7" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(Block6);

        jLabel8.setText("Processor1 cache");

        javax.swing.GroupLayout Line0StatePaneP1Layout = new javax.swing.GroupLayout(Line0StatePaneP1);
        Line0StatePaneP1.setLayout(Line0StatePaneP1Layout);
        Line0StatePaneP1Layout.setHorizontalGroup(
            Line0StatePaneP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        Line0StatePaneP1Layout.setVerticalGroup(
            Line0StatePaneP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        Line0StateLabelP1.setText("Shared");

        jLabel13.setText("Line 0");

        jLabel21.setText("Block no.");

        jLabel22.setText("Var no.");

        ReadBP1.setText("Read");
        ReadBP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadBP1ActionPerformed(evt);
            }
        });

        WriteBP1.setText("Write");
        WriteBP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriteBP1ActionPerformed(evt);
            }
        });

        jLabel23.setText("Value :");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditTextP1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WriteBP1)
                            .addComponent(jLabel23)
                            .addComponent(ReadBP1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ValueLabelP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValueLabelP1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReadBP1)
                .addGap(18, 18, 18)
                .addComponent(EditTextP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WriteBP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Line0StatePaneP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(Line0StateLabelP1)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel21)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(AddressP1BlockNo, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(AddressP1VariableNo)))
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Line0StatePaneP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Line0StateLabelP1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressP1BlockNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddressP1VariableNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        Line0P2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Line0P2.setModel(listModel0P2);
        Line0P2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane11.setViewportView(Line0P2);

        Block10.setBackground(new java.awt.Color(204, 204, 204));
        Block10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Block10.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Var 0", "Var 1", "Var 2", "Var 3", "Var 4", "Var 5", "Var 6", "Var 7" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane12.setViewportView(Block10);

        jLabel9.setText("Processor2 cache");

        javax.swing.GroupLayout Line0StatePaneP2Layout = new javax.swing.GroupLayout(Line0StatePaneP2);
        Line0StatePaneP2.setLayout(Line0StatePaneP2Layout);
        Line0StatePaneP2Layout.setHorizontalGroup(
            Line0StatePaneP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        Line0StatePaneP2Layout.setVerticalGroup(
            Line0StatePaneP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        Line0StateLabelP2.setText("Shared");

        jLabel16.setText("Line 0");

        jLabel25.setText("Var no.");

        jLabel26.setText("Block no.");

        ReadBP2.setText("Read");
        ReadBP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadBP2ActionPerformed(evt);
            }
        });

        WriteBP2.setText("Write");
        WriteBP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriteBP2ActionPerformed(evt);
            }
        });

        jLabel27.setText("Value :");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditTextP2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WriteBP2)
                            .addComponent(jLabel27)
                            .addComponent(ReadBP2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ValueLabelP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ValueLabelP2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReadBP2)
                .addGap(18, 18, 18)
                .addComponent(EditTextP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WriteBP2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel16))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel9))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Line0StatePaneP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(Line0StateLabelP2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(AddressP2BlockNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddressP2VariableNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Line0StatePaneP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Line0StateLabelP2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressP2BlockNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddressP2VariableNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        Line0P3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Line0P3.setModel(listModel0P3);
        Line0P3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane14.setViewportView(Line0P3);

        Block13.setBackground(new java.awt.Color(204, 204, 204));
        Block13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Block13.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Var 0", "Var 1", "Var 2", "Var 3", "Var 4", "Var 5", "Var 6", "Var 7" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane15.setViewportView(Block13);

        jLabel10.setText("Processor3 cache");

        jLabel18.setText("Line 0");

        jLabel29.setText("Var no.");

        jLabel30.setText("Block no.");

        ReadBP3.setText("Read");
        ReadBP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadBP3ActionPerformed(evt);
            }
        });

        WriteBP3.setText("Write");
        WriteBP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriteBP3ActionPerformed(evt);
            }
        });

        jLabel31.setText("Value :");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditTextP3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WriteBP3)
                            .addComponent(jLabel31)
                            .addComponent(ReadBP3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ValueLabelP3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ValueLabelP3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReadBP3)
                .addGap(18, 18, 18)
                .addComponent(EditTextP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WriteBP3)
                .addContainerGap())
        );

        Line0StateLabelP3.setText("Shared");

        javax.swing.GroupLayout Line0StatePaneP3Layout = new javax.swing.GroupLayout(Line0StatePaneP3);
        Line0StatePaneP3.setLayout(Line0StatePaneP3Layout);
        Line0StatePaneP3Layout.setHorizontalGroup(
            Line0StatePaneP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        Line0StatePaneP3Layout.setVerticalGroup(
            Line0StatePaneP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Line0StatePaneP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Line0StateLabelP3)
                        .addGap(195, 195, 195))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel30)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(AddressP3BlockNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddressP3VariableNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Line0StatePaneP3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Line0StateLabelP3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressP3BlockNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddressP3VariableNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(AnnouncePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(50, 50, 50)
                        .addComponent(AnnouncePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReadBP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadBP1ActionPerformed
        // TODO add your handling code here:
        //listModel0P1.clear();
          
        int k  = (int) AddressP1BlockNo.getValue() ; 
        DefaultListModel<Integer> listhere  = new DefaultListModel<>(); 
        
        if(valideP1>0)
        {
            if (k != blockNoP1)
                {

                    
                    if(listModel0P1.size()>0)
                    {
                        listhere.clear();
                        for(int i = 0 ; i <listModel0P1.size(); i++)
                        {
                            listhere.add(i,listModel0P1.elementAt(i));
                        }
                    }
                    listModelBlocks.remove(blockNoP1);
                     listModelBlocks.add(blockNoP1,listhere);
                     switch(blockNoP1)
                     {
                        case 0:
                             Block0.setModel(listModelBlocks.get(blockNoP1));
                             break;
                        case 1:
                            Block1.setModel(listModelBlocks.get(blockNoP1));
                            break;
                        case 2:
                            Block2.setModel(listModelBlocks.get(blockNoP1));
                            break;
                        case 3:
                            Block3.setModel(listModelBlocks.get(blockNoP1));
                            break;
                     }
                blockNoP1 = k ;
                }
        int varNo = (int) AddressP1VariableNo.getValue() ; 
        
        listhere = listModelBlocks.get(blockNoP1);
        listModel0P1.clear();
        for(int i = 0 ; i <listhere.size(); i++)
        {
            listModel0P1.add(i,listhere.elementAt(i));
        }
        ValueLabelP1.setText(String.format("%d",listModel0P1.elementAt(varNo)));
        
        
        }
        else
        {
            Announce.setText(String.format("%s %d","Processor 1 request block ",blockNoP1));
            AnnouncePanel.setBackground(Color.red);
            missedBlock = blockNoP1 ; 
        }
        
//        JOptionPane.showMessageDialog(null,"the printer is empty", "Error printing", JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_ReadBP1ActionPerformed

    private void WriteBP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteBP1ActionPerformed
        // TODO add your handling code here:
        int k  = (int) AddressP1BlockNo.getValue() ;
        int writeno = Integer.parseInt(EditTextP1.getText());
        int varNo = (int) AddressP1VariableNo.getValue() ; 
        DefaultListModel<Integer> listhere  = new DefaultListModel<>(); 

        if(valideP1>0)
        {
//            Line0StateLabelP1.setText("");
            if (k != blockNoP1)
                {

        //        listModelBlock0.set(0, 1); 
                
                    if(listModel0P1.size()>0)
                    {
                        listhere.clear();
                        for(int i = 0 ; i <listModel0P1.size(); i++)
                        {
                            listhere.add(i,listModel0P1.elementAt(i));
                        }
                    }
                    listModelBlocks.remove(blockNoP1);
                    listModelBlocks.add(blockNoP1,listhere);
                    switch(blockNoP1)
                     {
                        case 0:
                             Block0.setModel(listModelBlocks.get(blockNoP1));
                             break;
                        case 1:
                            Block1.setModel(listModelBlocks.get(blockNoP1));
                            break;
                        case 2:
                            Block2.setModel(listModelBlocks.get(blockNoP1));
                            break;
                        case 3:
                            Block3.setModel(listModelBlocks.get(blockNoP1));
                            break;
                     }
                    blockNoP1 = k ;
                }
            listModel0P1.set(varNo, writeno);
            //listModelBlocks.set(blockNoP1,listModel0P1);
            listModelBlocks.remove(blockNoP1);
            listModelBlocks.add(blockNoP1,listModel0P1);
                    switch(blockNoP1)
                     {
                        case 0:
                             Block0.setModel(listModelBlocks.get(blockNoP1));
                             break;
                        case 1:
                            Block1.setModel(listModelBlocks.get(blockNoP1));
                            break;
                        case 2:
                            Block2.setModel(listModelBlocks.get(blockNoP1));
                            break;
                        case 3:
                            Block3.setModel(listModelBlocks.get(blockNoP1));
                            break;
                     }
            if(blockNoP2==blockNoP1)
            {
                valideP2=0; 
                Line0StateLabelP2.setText("Invalid");
                Line0StatePaneP2.setBackground(Color.red);
                
            }
            if(blockNoP3==blockNoP1)
            {
                 valideP3=0; 
                Line0StateLabelP3.setText("Invalid");
                Line0StatePaneP3.setBackground(Color.red);
            }
            Line0StateLabelP1.setText("Exclusive");
            Line0StatePaneP1.setBackground(Color.blue);
            blockstate[blockNoP1]= 0 ; 
            valideP1=2; 
        }
        else
        {
            Announce.setText(String.format("%s %d","Processor 1 request block ",blockNoP1));
            AnnouncePanel.setBackground(Color.red);
            missedBlock = blockNoP1 ; 
        }
        
    }//GEN-LAST:event_WriteBP1ActionPerformed

    private void ReadBP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadBP2ActionPerformed
        // TODO add your handling code here:
          
        int k  = (int) AddressP2BlockNo1.getValue() ; 
        DefaultListModel<Integer> listhere  = new DefaultListModel<>(); 
        
        if(valideP2>0)
        {
            if (k != blockNoP2)
                {

        //        listModelBlock0.set(0, 1); 
                    
                    if(listModel0P2.size()>0)
                    {
                        listhere.clear();
                        for(int i = 0 ; i <listModel0P2.size(); i++)
                        {
                            listhere.add(i,listModel0P2.elementAt(i));
                        }
                    }
                     listModelBlocks.remove(blockNoP2);
                     listModelBlocks.add(blockNoP2,listhere);
                     switch(blockNoP2)
                     {
                        case 0:
                             Block0.setModel(listModelBlocks.get(blockNoP2));
                             break;
                        case 1:
                            Block1.setModel(listModelBlocks.get(blockNoP2));
                            break;
                        case 2:
                            Block2.setModel(listModelBlocks.get(blockNoP2));
                            break;
                        case 3:
                            Block3.setModel(listModelBlocks.get(blockNoP2));
                            break;
                     }
                blockNoP2 = k ;
                }
        int varNo = (int) AddressP2VariableNo1.getValue() ; 
        
        listhere = listModelBlocks.get(blockNoP2);
        listModel0P2.clear();
        for(int i = 0 ; i <listhere.size(); i++)
        {
            listModel0P2.add(i,listhere.elementAt(i));
        }
        ValueLabelP2.setText(String.format("%d",listModel0P2.elementAt(varNo)));
        
        
        }
        else
        {
            Announce.setText(String.format("%s %d","Processor 2 request block ",blockNoP2));
            AnnouncePanel.setBackground(Color.red);
            missedBlock = blockNoP2 ; 
        }
        
    }//GEN-LAST:event_ReadBP2ActionPerformed

    private void WriteBP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteBP2ActionPerformed
        // TODO add your handling code here:
        int k  = (int) AddressP2BlockNo1.getValue() ;
        int writeno = Integer.parseInt(EditTextP2.getText());
        int varNo = (int) AddressP2VariableNo1.getValue() ; 
        DefaultListModel<Integer> listhere  = new DefaultListModel<>(); 

        if(valideP2>0)
        {
//            Line0StateLabelP1.setText("");
            if (k != blockNoP2)
                {

        //        listModelBlock0.set(0, 1); 
                
                    if(listModel0P2.size()>0)
                    {
                        listhere.clear();
                        for(int i = 0 ; i <listModel0P2.size(); i++)
                        {
                            listhere.add(i,listModel0P2.elementAt(i));
                        }
                    }
                    listModelBlocks.remove(blockNoP2);
                    listModelBlocks.add(blockNoP2,listhere);
                    switch(blockNoP2)
                     {
                        case 0:
                             Block0.setModel(listModelBlocks.get(blockNoP2));
                             break;
                        case 1:
                            Block1.setModel(listModelBlocks.get(blockNoP2));
                            break;
                        case 2:
                            Block2.setModel(listModelBlocks.get(blockNoP2));
                            break;
                        case 3:
                            Block3.setModel(listModelBlocks.get(blockNoP2));
                            break;
                     }
                    blockNoP2 = k ;
                }
            listModel0P2.set(varNo, writeno);
            listModelBlocks.remove(blockNoP2);
            listModelBlocks.add(blockNoP2,listModel0P2);
                    switch(blockNoP2)
                     {
                        case 0:
                             Block0.setModel(listModelBlocks.get(blockNoP2));
                             break;
                        case 1:
                            Block1.setModel(listModelBlocks.get(blockNoP2));
                            break;
                        case 2:
                            Block2.setModel(listModelBlocks.get(blockNoP2));
                            break;
                        case 3:
                            Block3.setModel(listModelBlocks.get(blockNoP2));
                            break;
                     }
            if(blockNoP1==blockNoP2)
            {
                valideP1=0; 
                Line0StateLabelP1.setText("Invalid");
                Line0StatePaneP1.setBackground(Color.red);
                
            }
            if(blockNoP3==blockNoP2)
            {
                 valideP3=0; 
                Line0StateLabelP3.setText("Invalid");
                Line0StatePaneP3.setBackground(Color.red);
            }
            Line0StateLabelP2.setText("Exclusive");
            Line0StatePaneP2.setBackground(Color.blue);
            blockstate[blockNoP2]= 0 ; 
            valideP2 = 2 ; 
        }
        else
        {
            Announce.setText(String.format("%s %d","Processor 1 request block ",blockNoP2));
            AnnouncePanel.setBackground(Color.red);
            missedBlock = blockNoP2 ; 
        }
    }//GEN-LAST:event_WriteBP2ActionPerformed

    private void ReadBP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadBP3ActionPerformed
        // TODO add your handling code here:
         int k  = (int) AddressP3BlockNo2.getValue() ; 
        DefaultListModel<Integer> listhere  = new DefaultListModel<>(); 
        
        if(valideP3>0)
        {
            if (k != blockNoP3)
                {

        //        listModelBlock0.set(0, 1); 
                    
                    if(listModel0P3.size()>0)
                    {
                        listhere.clear();
                        for(int i = 0 ; i <listModel0P3.size(); i++)
                        {
                            listhere.add(i,listModel0P3.elementAt(i));
                        }
                    }
                     listModelBlocks.remove(blockNoP3);
                     listModelBlocks.add(blockNoP3,listhere);
                     switch(blockNoP3)
                     {
                        case 0:
                             Block0.setModel(listModelBlocks.get(blockNoP3));
                             break;
                        case 1:
                            Block1.setModel(listModelBlocks.get(blockNoP3));
                            break;
                        case 2:
                            Block2.setModel(listModelBlocks.get(blockNoP3));
                            break;
                        case 3:
                            Block3.setModel(listModelBlocks.get(blockNoP3));
                            break;
                     }
                blockNoP3 = k ;
                }
        int varNo = (int) AddressP3VariableNo2.getValue() ; 
        
        listhere = listModelBlocks.get(blockNoP3);
        listModel0P3.clear();
        for(int i = 0 ; i <listhere.size(); i++)
        {
            listModel0P3.add(i,listhere.elementAt(i));
        }
        ValueLabelP3.setText(String.format("%d",listModel0P3.elementAt(varNo)));
        
        
        }
        else
        {
            Announce.setText(String.format("%s %d","Processor 3 request block ",blockNoP3));
            AnnouncePanel.setBackground(Color.red);
            missedBlock = blockNoP2 ; 
        }
    }//GEN-LAST:event_ReadBP3ActionPerformed

    private void WriteBP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteBP3ActionPerformed
        // TODO add your handling code here:
        int k  = (int) AddressP3BlockNo2.getValue() ;
        int writeno = Integer.parseInt(EditTextP3.getText());
        int varNo = (int) AddressP3VariableNo2.getValue() ; 
        DefaultListModel<Integer> listhere  = new DefaultListModel<>(); 

        if(valideP3>0)
        {
//            Line0StateLabelP1.setText("");
            if (k != blockNoP3)
                {

        //        listModelBlock0.set(0, 1); 
                
                    if(listModel0P3.size()>0)
                    {
                        listhere.clear();
                        for(int i = 0 ; i <listModel0P3.size(); i++)
                        {
                            listhere.add(i,listModel0P3.elementAt(i));
                        }
                    }
                    listModelBlocks.remove(blockNoP3);
                    listModelBlocks.add(blockNoP3,listhere);
                    switch(blockNoP3)
                     {
                        case 0:
                             Block0.setModel(listModelBlocks.get(blockNoP3));
                             break;
                        case 1:
                            Block1.setModel(listModelBlocks.get(blockNoP3));
                            break;
                        case 2:
                            Block2.setModel(listModelBlocks.get(blockNoP3));
                            break;
                        case 3:
                            Block3.setModel(listModelBlocks.get(blockNoP3));
                            break;
                     }
                    blockNoP3 = k ;
                }
            listModel0P3.set(varNo, writeno);
            listModelBlocks.remove(blockNoP3);
            listModelBlocks.add(blockNoP3,listModel0P3);
                    switch(blockNoP3)
                     {
                        case 0:
                             Block0.setModel(listModelBlocks.get(blockNoP3));
                             break;
                        case 1:
                            Block1.setModel(listModelBlocks.get(blockNoP3));
                            break;
                        case 2:
                            Block2.setModel(listModelBlocks.get(blockNoP3));
                            break;
                        case 3:
                            Block3.setModel(listModelBlocks.get(blockNoP3));
                            break;
                     }
            if(blockNoP1==blockNoP3)
            {
                valideP1=0; 
                Line0StateLabelP1.setText("Invalid");
                Line0StatePaneP1.setBackground(Color.red);
                
            }
            if(blockNoP2==blockNoP3)
            {
                 valideP2=0; 
                Line0StateLabelP2.setText("Invalid");
                Line0StatePaneP2.setBackground(Color.red);
            }
            Line0StateLabelP3.setText("Exclusive");
            Line0StatePaneP3.setBackground(Color.blue);
            blockstate[blockNoP3]= 0 ; 
            valideP3 = 2 ; 
        }
        else
        {
            Announce.setText(String.format("%s %d","Processor 3 request block ",blockNoP3));
            AnnouncePanel.setBackground(Color.red);
            missedBlock = blockNoP3 ; 
        }
    }//GEN-LAST:event_WriteBP3ActionPerformed

    private void ShareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShareButtonActionPerformed
        // TODO add your handling code here:
        DefaultListModel<Integer> listhere  = new DefaultListModel<>();
        switch(blockstate[missedBlock])
        {
            case 0:
                listhere = listModel0P1;
                listModelBlocks.set(missedBlock,listModel0P1);
                break;
            case 1:
                 listhere = listModel0P2;
                 listModelBlocks.set(missedBlock,listModel0P2);
                break;
            case 2: 
                listhere = listModel0P3;
                listModelBlocks.set(missedBlock,listModel0P3);
                break;
            default:
                 listhere = listModelBlocks.get(missedBlock);
                break;
            
        }
        if(valideP1!=1)
        {
            Line0StateLabelP1.setText("Shared");
            Line0StatePaneP1.setBackground(Color.green);
            if(valideP1==0)
            {
                listModel0P1.clear();
                            for(int i = 0 ; i <listhere.size(); i++)
                            {
                                listModel0P1.add(i,listhere.elementAt(i));
                            }
                valideP1 = 1 ;
            }
        }
        if(valideP2!=1)
        {
            Line0StateLabelP2.setText("Shared");
            Line0StatePaneP2.setBackground(Color.green);
            if(valideP2==0)
            {
                listModel0P2.clear();
                            for(int i = 0 ; i <listhere.size(); i++)
                            {
                                listModel0P2.add(i,listhere.elementAt(i));
                            }
                valideP2 = 1 ;
            }
        }
        if(valideP3!=1)
        {
            Line0StateLabelP3.setText("Shared");
            Line0StatePaneP3.setBackground(Color.green);
            if(valideP3==0)
            {
                listModel0P3.clear();
                            for(int i = 0 ; i <listhere.size(); i++)
                            {
                                listModel0P3.add(i,listhere.elementAt(i));
                            }
                valideP3 = 1 ;
            }
        }
        Announce.setText("Shared for each request");
        AnnouncePanel.setBackground(Color.black);
        
    }//GEN-LAST:event_ShareButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnoopingTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnoopingTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnoopingTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnoopingTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnoopingTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AddressP1BlockNo;
    private javax.swing.JSpinner AddressP1VariableNo;
    private javax.swing.JSpinner AddressP2BlockNo1;
    private javax.swing.JSpinner AddressP2VariableNo1;
    private javax.swing.JSpinner AddressP3BlockNo2;
    private javax.swing.JSpinner AddressP3VariableNo2;
    private javax.swing.JLabel Announce;
    private javax.swing.JPanel AnnouncePanel;
    private javax.swing.JList Block0;
    private javax.swing.JList Block1;
    private javax.swing.JList Block10;
    private javax.swing.JList Block13;
    private javax.swing.JList Block2;
    private javax.swing.JList Block3;
    private javax.swing.JList Block4;
    private javax.swing.JList Block6;
    private javax.swing.JTextField EditTextP1;
    private javax.swing.JTextField EditTextP2;
    private javax.swing.JTextField EditTextP3;
    private javax.swing.JList Line0P1;
    private javax.swing.JList Line0P2;
    private javax.swing.JList Line0P3;
    private javax.swing.JLabel Line0StateLabelP1;
    private javax.swing.JLabel Line0StateLabelP2;
    private javax.swing.JLabel Line0StateLabelP3;
    private javax.swing.JPanel Line0StatePaneP1;
    private javax.swing.JPanel Line0StatePaneP2;
    private javax.swing.JPanel Line0StatePaneP3;
    private javax.swing.JButton ReadBP1;
    private javax.swing.JButton ReadBP2;
    private javax.swing.JButton ReadBP3;
    private javax.swing.JButton ShareButton;
    private javax.swing.JLabel ValueLabelP1;
    private javax.swing.JLabel ValueLabelP2;
    private javax.swing.JLabel ValueLabelP3;
    private javax.swing.JButton WriteBP1;
    private javax.swing.JButton WriteBP2;
    private javax.swing.JButton WriteBP3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
private DefaultListModel<Integer> listModel0P1;
private DefaultListModel<Integer> listModel1P1;
private DefaultListModel<Integer> listModel0P2;
private DefaultListModel<Integer> listModel1P2;
private DefaultListModel<Integer> listModel0P3;
private DefaultListModel<Integer> listModel1P3;
private ArrayList <DefaultListModel<Integer>> listModelBlocks;
//private DefaultListModel<Integer> listModelBlock1;
//private DefaultListModel<Integer> listModelBlock2;
//private DefaultListModel<Integer> listModelBlock3;
int[] blockstate = {-1,-1, -1 ,-1} ; 
 
int missedBlock = 0 ; 
int valideP1 = 0 ; 
int valideP2 = 0 ; 
int valideP3 = 0 ; 
int blockNoP1 = 0 ; 
int blockNoP2 = 0 ; 
int blockNoP3 = 0 ; 
	  
}
